development:
  sessions:
    default:
      database: launch_window
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false
production:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
  options:
    raise_not_found_error: false
test:
  sessions:
    default:
      database: launch_window
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false
